const express = require("express")
const router = express.Router()

var allBlogs = require("../controllers/blog/allBlogs")
var createGet = require("../controllers/blog/createGet")
var createPost = require("../controllers/blog/createPost")
var deleteGet = require("../controllers/blog/deleteGet")
var deletePost = require("../controllers/blog/deletePost")
var singleBlog = require("../controllers/blog/singleBlog")
var updateGet = require("../controllers/blog/updateGet")
var updatePost = require("../controllers/blog/updatePost")
var loginGet = require("../controllers/user/loginGet")
var loginPost = require("../controllers/user/loginPost")
var registerGet = require("../controllers/user/registerGet")
var registerPost = require("../controllers/user/registerPost")
var aboutPage = require("../controllers/hp/about")
var worksPage = require("../controllers/hp/works")
var skillPage = require("../controllers/hp/skill")
var contactPage = require("../controllers/hp/contact")

router.get("/", allBlogs)
router.get("/about", aboutPage)
router.get("/works", worksPage)
router.get("/skill", skillPage)
router.get("/contact", contactPage)
router.get("/blog/create", createGet)
router.post("/blog/create", createPost)
router.get("/blog/delete/:id", deleteGet)
router.post("/blog/delete/:id", deletePost)
router.get("/blog/:id", singleBlog)
router.get("/blog/update/:id", updateGet)
router.post("/blog/update/:id", updatePost)
router.get("/user/login", loginGet)
router.post("/user/login", loginPost)
router.get("/user/create", registerGet)
router.post("/user/create", registerPost)

module.exports = router